@startuml C4_Container_Detailed
!include <C4/C4_Container>

title Депозитарная система АБС банка «Стандарт»

SHOW_PERSON_OUTLINE()
LAYOUT_WITH_LEGEND()

Person(customer_online, "Клиент (интернет-банк)", "Авторизованный клиент")
Person(customer_new, "Новый клиент (сайт)", "Клиент для привлечения")
Person(manager_cc, "Менеджер кол-центра", "Консультирование")


System_Boundary(system, "АБС «Банк Стандарт»", "ABS") {
    Person(manager_bo, "Менеджер бэк-офиса", "Обработка заявок")
    Person(manager_rates, "Менеджер ставок", "Управление ставками")
    Boundary(internet_bank, Интернет-банк) {
        Container("ui_mf_host", "Module Federation Host", "JavaScript, React, Module Federation Host", "frontend\nbuild-time compositor")

        Container("ui_main_mf_build", "Интернет-банк, основной UI", "TypeScript, React, Module Federation expose", microfrontend)
        Container("ui_deposit_mf_build", "Интернет-банк, UI депозитов", "JavaScript, React, Module Federation expose", microfrontend)
        Container("ui_deposit_manager", "UI депозитов оператора банка", "TypeScript, React", frontend)

        Container("kong", "API gateaway", "Kong", "reverse proxy\nrate limiting, authentication, load balancing")

        Container("deposit_back", "Процессинг депозитов", "Java, Spring", backend app)
        ContainerDb("deposit_db", "БД депозитов", "PostgreSQL", "storage")
    }
    System(website, "Сайт банка", "Привлечение новых клиентов")
    System(abs, "АБС (Core)", "Управление счетами, депозитами, СМС")
    System(rate_system, "Система управления ставками", "Расчёт и хранение ставок")
    System(risk_system, "Система оценки кредитного риска", "Анализ риска банка")
    System(cc_system, "Система кол-центра", "Управление обращениями")
    ContainerQueue(events, "Горизонтальное взаимодействие служб", "Kafka", "event sourcing bus")
}

System_Ext(partner_cc, "Партнёрский кол-центр", "Внешний провайдер")
System_Ext(external_bank, "ЦБ РФ", "Ставка рефинансирования")

Rel(customer_new, website, "Подаёт заявку, видит ставки")
Rel(manager_bo, abs, "Обработка заявок, согласование")
Rel(manager_cc, cc_system, "Консультирование, заявки")
Rel(manager_cc, rate_system, "Просмотр ставок")
Rel(manager_rates, rate_system, "Управление ставками")
Rel(partner_cc, rate_system, "Получение ставок (SFTP)")
Rel(internet_bank, rate_system, "Загрузка ставок")
Rel(internet_bank, abs, "Подача заявок (асинхронно)")
Rel(website, cc_system, "Передача заявок")
Rel(abs, customer_online, "СМС-уведомления")
Rel(rate_system,external_bank, "Ставка ЦБ (ежедневно)")
Rel(rate_system,risk_system, "Уровень кредитного риска")
Rel(cc_system, abs, "Связь с АБС")

Rel(customer_online, ui_mf_host, "browser")
Rel(ui_mf_host, ui_deposit_mf_build, "request", "sync, rest")
Rel(ui_mf_host, ui_main_mf_build, "request", "sync, rest")

Rel(ui_main_mf_build, kong, "request", "sync, rest")
Rel(ui_deposit_mf_build, kong, "request", "sync, rest")
Rel(ui_deposit_manager, kong, "request", "sync, rest")

Rel(kong, deposit_back, "request", "sync, rest")
Rel_R(kong, abs, "request", "sync, rest")
Rel(deposit_back, deposit_db, , "socket")

Rel_D(manager_rates, "ui_deposit_manager", "Подаёт заявку, видит ставки")

Rel_R(deposit_back, events, event, "async, kafka")
Rel_U(events, abs, event, "async, kafka")

@enduml